### ISSUE TITLE
Exception on rendering map

### ISSUE THREAD

**Issue by lazybadger** [finanalyst/grav-plugin-map-marker-leaflet#17]
`Undefined variable: tilestanza` on rendering template mapleaflet.html.twig after GPM-install of plugin and attempt to use samples from readme.
And yes, this variable defined in yaml
```yaml
providers:
  openstreetmap:
    tilestanza: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
```
